name       : kid3
version    : 3.4.5
release    : 1
source     :
    - https://prdownloads.sourceforge.net/kid3/kid3-3.4.5.tar.gz : 0d703b0b8c2538eba1f8f540a87e13a4bf61f715ef9cd1253f18417ebb096404
license    : GPL-2.0
component  : multimedia.audio
summary    : 
    - Efficient audio tagger
    - cli: Audio tagger command-line-interface
    - core: Audio tagger core libraries and data 
description: 
    - Efficient audio tagger
    - cli: Kid3-cli offers a command-line-interface for Kid3, for a GUI use kid3-qt.
    - core: This package contains libraries and data used by kid3-qt and kid3-cli.
    - qt: Kid3 audio tag editor can edit the tags of MP3, Ogg, FLAC, MPC and WMA files in an efficient way, convert between ID3v1 and ID3v2, set the tags of multiple files, generate tags from file names or vice versa and import from freedb, MusicBrainz and Disco.
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(gl)
    - pkgconfig(libavcodec)
    - pkgconfig(libchromaprint)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(taglib)
    - pkgconfig(vorbis)
    - id3lib-devel
    - kdoctools-devel
rundeps:
    - cli: kid3-core
    - qt: kid3-core
patterns:
    - core: /*
    - cli:
        - /usr/bin/kid3-cli
        - /usr/share/man/de/man1/kid3-cli.1.gz
        - /usr/share/man/man1/kid3-cli.1.gz
    - qt:
        - /usr/bin/kid3-qt
        - /usr/share/appdata
        - /usr/share/applications
        - /usr/share/doc
        - /usr/share/icons
        - /usr/share/man/de/man1/kid3-qt.1.gz
        - /usr/share/man/man1/kid3-qt.1.gz
setup      : |
    %cmake . -DWITH_APPS="Qt;CLI"
build      : |
    %make
install    : |
    %make_install
